### ISSUE TITLE
Generated code is missing first character in imported files

### ISSUE THREAD

**Issue by brunoluiz** [appointy/protoc-gen-jaal#3]
The generated output for some stuff is missing the first character. Example:

```golang
func RegisterInputustomer_Xyz(schema *schemabuilder.Schema) {
	input := schema.InputObject("SomeInput", ustomer_Xyz{})

	input.FieldFunc("status", func(target *ustomer_Xyz, source Status) {
		target.Status = source
	})
```

**Comment by brunoluiz** [comment]
Having a quick glance through the `methods.go`, it might be because of `*` in front of some structures. Example:

```
			if fieldFuncSecondParaFuncPara[0] == '*' {
				fieldFuncSecondParaFuncPara = fieldFuncSecondParaFuncPara[1:len(fieldFuncSecondParaFuncPara)]
			}
```

I've tried to remove some of these to see if it works, it doesn't tho

**Comment by anujdecoder** [comment]
Please post the proto for which this bug occurred.

**Comment by brunoluiz** [comment]
Okay, I found a way to mimic the behaviour. Here it is:

`api.proto`:
```protobuf
syntax = "proto3";

import "schema/schema.proto";
import "details.proto";

// Defines where your go package will be placed after compiled
option go_package = "api";

service Everything {
  rpc GetThings (GetThingsRequest) returns (GetThingsResponse) {
    option (graphql.schema) = {
        query : "users"
    };
  }
}

message Something {
  string id = 1;
  repeated Item items = 2;

  message Item {
    string id = 1;
    Details details = 2;
  }
}

message GetThingsRequest {
  string bucket_id = 1;
}

message GetThingsResponse {
  repeated Something things = 1;
}
```

`details.proto`:
```protobuf
syntax = "proto3";

option go_package = "api";

enum SomeStatus {
  SomeStatusUnknown = 0;
  SomeStatusOk = 1;
  SomeStatusFailed = 2;
}

message Details {
  SomeStatus status = 1;
}
```

```
	protoc \
		-I./api \
		-I$(GOPATH)/src \
		-I$(GOPATH)/src/go.appointy.com/protoc-gen-jaal \
		--go_out=plugins=grpc:./generated \
		--jaal_out=./generated \
		api.proto
```

And you might be able to see some variables/structs with the missing lead character.

One thing I noted while trying to create a reproducible example: this only happens to imported stuff. If you move whatever is in `details.proto` to `api.proto` then it works.

Let me know if you need more details ;)

**Comment by brunoluiz** [comment]
Perhaps I am doing something wrong on my protoc call? Can I have a light on this one?

**Comment by anujdecoder** [comment]
The issue is not in the imported files. It is in the embedded message. The plugin was not generating expected code for embedded messages.  The issue has been resolved.
